sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: YLwItpdomK7wtJcgxGapgJPBwznafsqDajWnqU7FRUzbIDPfx8odpQEpsdTsHJrz5GNsq/qQ+fwvcLKJ6t892hrW1bVB7otmZt+cwuGh4AcNOZ81GCGOJrMp7gEDaZIZeL+Q+hGnKD04e0O9tVR8EsZgp7dPTwivFl8UDamnSzRi4ekVYsrqG0Sz1VQXX5v3XAXK6GcbW2jgCqpZvPAJhvdthjIBSbHxM9WbcVtKni7wj6mjyu1X59CLEm/ZLs3Po/7dvaqViu2ctcFfb5rr+VYWd57jdrOzGCa0di8jqrunxb+nX47+y0dt+bdbcd9d8+4FKfvguQnzvSCe48fw1QV0IS/LSNSoIVU0bRLMs7lobQ4nOriq9Q/7fvcHAuuchN2TV7BquiTCFRVlKySHCyABdkojdjFtLw9czDGMVRxYkllwaKY2w8XdV11Kxw0hRwGzXXg6VUNXTgK+QX7DnRR4u/0xJin16Rhk8AG2FeGbQD9y7mWo6NDP+ssG01AV/VBLFhGGAW+1eitaF5nbeMQkgd3u/VSH4W+lT+2VAGWNEFEGa7jPL1WWNchgoXJrw8FxEkctgQsGsEhPmMS75wGQZO7K+j8FCWnzwvhKDqfTKSrKEi0jhBfe3QXgRPIfaXYcTvkc9mUOI3W+5USNNvxGTktB+Q4/i5JYyYLaPRU=
  - secure: BfWra272jWMAD9ISfjnNuPV4FvkvQbv2I9+uEWxu5C8xdNVkTbo9/nrhXPxuHtWUHxpCTGdnM1r+KeiVPuhphPDVT+rciegAyDGOEh0v9VnHGI92zkK7QSFye+JhBgDDRpHhS6HrBkAgbcu4V0Xru16ju+2Pn0VsmFzBQXckMTRHJxf4uX02hKFYPBpG5+Uhr3ylGYQFrZUKOIDVhFzIWFje2tc/ZKT9ikXK2NMtGcY7CD7hWj7ZUNcnKNTg7Uy2/kTSf63DEhiTRbxXr79bKcNgLIi3yIolNzb6OcmFfVJnloWR5m4w0CI59fKlw95tWi968HGjiHELSGBBg5+aW5PaMwG4BhJi5mVmZ9RAm4anpu1ZYtVePtA0S5n0odpE1rwugbP1m6ukZNYKgBJpOcmCt7virYqsUfiV26xfrRjDtrzWBzzHRBY1u4W4m1q3uNVz6N9/Tz3TVVR8HxrvTGZhpWmMFzvphSOI1DEYn7uvoneTxxRLU8D0y8wbiheNEHeGEvWA0G8HH0rsmz6gsXZnEibBQb7ISTzO9EmPlAkrpr9WQlmhMYwiKeJVq3Gdy0u8yGeMI0jeIYBMOZBzwtNmQy6Rh6ogzJYNtDNka270hMJm98qYzTJnUZ3qB9JCPtLW2EZRS/JdGngni2MXpOwXhaBqunL3ehL5C+UWQNM=
  - secure: k5hZdr71TUpa5zesH6XeIdM3OdIrl7KD55V2c9almvoGDLPD4PiarEXlnVbThtq73cXSTqmd5K1Xz7cSxOthWG/B/LxHLFScbHVY+GFYvqJu9KpooD4BmMpJu9lbfHUE+oBtmPiqmUQds3Kc1OZGLSwsdc3eAI7wVn44xn8MB2Tdht3rOvLpGb7HQBGha6PfG++Kon6JKHHnrc40NlXVv0h75kfuLPp5BuF84VupIfWX0qRh/zqWq8RRhZ+DkzOKaXZS5VSyB73IabYMOtYAxQIjjggT6z6yZlX8lyfEEW2siNLP6Ea5agIPrXmLEgqFh6NtVandqD3yQRuKfFfIbbMByiqBPd8yUCQZNjIwi+uS+oMsf+YnzcVWIfvVhIViX4dCA5XGIUnWhTW233Lz9pAQDmjejgM1KhgH1NxPtfpfbrv5Du7BmOcqUIneXZc0EzD5HA9nJdVQCRG838XuN9KdakvU3Wo6/zKBGxFUTmb7nuLFw2ahtHBNWShnuap+fQXuU0dlOUZVCuvYhLurCGumq4wzIQaycQ7r9McelCfv75iPfMX3/YQRJEPvCKruTJXy4uohxOao9Vsc1XepcRizP0YlsJaMjJd5ChvIdrks5+cx1O6cTK/sn/Au9CHFu/+B/Lakm93MjRCTuZMP1maLqMfh7QI8UyI4cfdLsU4=
